# Generated by Django 3.2.3 on 2021-05-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coches',
            fields=[
                ('Uid', models.AutoField(primary_key=True, serialize=False)),
                ('Cfabricante', models.CharField(max_length=100)),
                ('CPotencia', models.FloatField(max_length=100)),
                ('Ccentimetros', models.FloatField(max_length=100)),
                ('CColor', models.CharField(max_length=100)),
                ('CMxPas', models.IntegerField(max_length=1)),
                ('Cpeso', models.FloatField(max_length=100)),
            ],
        ),
    ]
