# Generated by Django 3.2.1 on 2021-05-18 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_auto_20210517_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comerciales',
            fields=[
                ('codComercial', models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='Código de comercial')),
                ('nombre', models.CharField(default='aaa', max_length=30, verbose_name='Nombre')),
                ('apellidos', models.CharField(default='', max_length=30, verbose_name='Apellidos')),
                ('fechaInc', models.DateField(default=1, max_length=10, verbose_name='Fecha incorporación')),
                ('comision', models.CharField(default='', max_length=4, verbose_name='Comisión')),
            ],
        ),
        migrations.AlterField(
            model_name='coches',
            name='CNombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='coches',
            name='CcodComercial',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CRUD.comerciales', verbose_name='Comercial asignado'),
        ),
    ]
