# Generated by Django 3.2.1 on 2021-05-19 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_auto_20210518_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coches',
            name='CColor',
            field=models.CharField(max_length=100, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='coches',
            name='CMxPas',
            field=models.IntegerField(verbose_name='Pasajeros'),
        ),
        migrations.AlterField(
            model_name='coches',
            name='CNombre',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='coches',
            name='CPotencia',
            field=models.FloatField(max_length=100, verbose_name='Potencia'),
        ),
        migrations.AlterField(
            model_name='coches',
            name='Ccentimetros',
            field=models.FloatField(max_length=100, verbose_name='Centimetros'),
        ),
        migrations.AlterField(
            model_name='coches',
            name='CcodComercial',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CRUD.comerciales', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='coches',
            name='Cfabricante',
            field=models.CharField(max_length=100, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='coches',
            name='Cpeso',
            field=models.FloatField(max_length=100, verbose_name='Peso'),
        ),
    ]
